version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:4.1
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . bucket_env/Scripts/activate
            python file_storage/manage.py test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results/
          destination: python_app


